backend:
  name: git-gateway
  branch: master

display_url: https://santacontabilidade.com.br/
media_folder: static/assets
public_folder: /assets

collections:
  - name: 'pages'
    label: 'Paginas'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/pages/blog.md'
        label: 'Blog Page'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }

  - name: posts
    label: Criar Posts
    editor:
      preview: false
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true 
    fields: 
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Date, name: date, widget: datetime, format: 'DD/MM/YYYY' }
      - label: 'Categorias de Post'
        name: 'categories'
        widget: 'list'
        fields:
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      - { label: Titulo, name: title, widget: string }
      - { label: SubTitulo, name: subtitle, widget: text }
      - {
        label: Imagem,
        name: featuredImage,
        widget: image
      }
      - { label: Tempo de Leitura, name: leitura, widget: string }
      - label: 'Post: Conteudo e Boxes'
        name: 'contentbody'
        widget: 'list'
        types:
        - label: 'Bloco de Conteudo'
          name: 'addbodypost'
          fields:
            - { name: bodypost, label: Bloco de Conteudo, widget: markdown }
        - label: 'Green Box'
          name: 'addgreenbox'
          fields:
            - { name: greenboxtitle, label: Green Box Titulo, widget: string }
            - { name: greenboxtitlebutton, label: Green Box Titulo Botao, widget: string }
            - { name: greenboxlink, label: Green Box Link, widget: string }
        - label: 'Yellow Box'
          name: 'addyellowbox'
          fields:
            - { name: yellowboxtitle, label: Yellow Box Titulo, widget: string }
            - { name: yellowboxlink, label: Yellow Box Link, widget: string }
      - label: 'Autor'
        name: 'autor'
        widget: 'list'
        fields:
          - label: 'Autor Name'
            name: 'autorname'
            widget: 'relation'
            collection: 'autores'
            searchFields: ['title']
            valueField: 'title'
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['AllPosts', 'Destaque']
        default: 'AllPosts'

  - name: postCategories
    label: Criar Categoria de Post
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogIndex }
      - { label: Title, name: title, widget: string }

  - name: autores
    label: Criar Autor
    editor:
      preview: false
    folder: content/autores
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Nome, name: title, widget: string }
      - { label: About, name: about, widget: text }
      - { label: Linkedin, name: linkedin, widget: string }
      - {
        label: Imagem,
        name: featuredImage,
        widget: image
      }

  - name: material
    label: Criar Material
    folder: content/material
    slug: '{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Titulo, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: link, label: Link, widget: string }
      - label: Image
        name: image
        widget: image
        required: false
        media_library:
          config:
            multiple: false
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["Destaque", "Materiais" ]
        default: ["Materiais"]

  - name: 'settings'
    label: 'Settings'
    delete: false 
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
